name: Build Design Tokens

on:
  push:
    paths:
      - 'src/tokens/**.json'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Style Dictionary
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: design-tokens-output
          path: build
